# Generated by Django 3.0.4 on 2020-04-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('age', models.CharField(max_length=150)),
                ('height_cm', models.CharField(max_length=150)),
                ('weight_kg', models.CharField(max_length=150)),
                ('overall', models.CharField(max_length=150)),
                ('player_positions', models.CharField(max_length=150)),
                ('weak_foot', models.CharField(max_length=150)),
                ('skill_moves', models.CharField(max_length=150)),
                ('attacking_crossing', models.CharField(max_length=150)),
                ('attacking_finishing', models.CharField(max_length=150)),
                ('attacking_heading_accuracy', models.CharField(max_length=150)),
                ('attacking_short_passing', models.CharField(max_length=150)),
                ('attacking_volleys', models.CharField(max_length=150)),
                ('skill_dribbling', models.CharField(max_length=150)),
                ('skill_curve', models.CharField(max_length=150)),
                ('skill_fk_accuracy', models.CharField(max_length=150)),
                ('skill_long_passing', models.CharField(max_length=150)),
                ('skill_ball_control', models.CharField(max_length=150)),
                ('movement_acceleration', models.CharField(max_length=150)),
                ('movement_sprint_speed', models.CharField(max_length=150)),
                ('movement_agility', models.CharField(max_length=150)),
                ('movement_reactions', models.CharField(max_length=150)),
                ('movement_balance', models.CharField(max_length=150)),
                ('power_shot_power', models.CharField(max_length=150)),
                ('power_jumping', models.CharField(max_length=150)),
                ('power_stamina', models.CharField(max_length=150)),
                ('power_strength', models.CharField(max_length=150)),
                ('power_long_shots', models.CharField(max_length=150)),
                ('mentality_aggression', models.CharField(max_length=150)),
                ('mentality_interceptions', models.CharField(max_length=150)),
                ('mentality_positioning', models.CharField(max_length=150)),
                ('mentality_vision', models.CharField(max_length=150)),
                ('mentality_penalties', models.CharField(max_length=150)),
                ('mentality_composure', models.CharField(max_length=150)),
                ('defending_marking', models.CharField(max_length=150)),
                ('defending_standing_tackle', models.CharField(max_length=150)),
                ('defending_sliding_tackle', models.CharField(max_length=150)),
                ('goalkeeping_diving', models.CharField(max_length=150)),
                ('goalkeeping_handling', models.CharField(max_length=150)),
                ('goalkeeping_kicking', models.CharField(max_length=150)),
                ('goalkeeping_positioning', models.CharField(max_length=150)),
                ('goalkeeping_reflexes', models.CharField(max_length=150)),
                ('estimate', models.CharField(max_length=150)),
                ('dt', models.CharField(max_length=150)),
                ('tm', models.CharField(max_length=150)),
            ],
        ),
    ]
